import { NextRequest, NextResponse } from 'next/server'

export async function POST(req: NextRequest) {
  try {
    const data = await req.json()

    if (!data || !data.product || !data.currentClassification || !data.opportunities) {
      return NextResponse.json(
        { error: 'Invalid analysis data' },
        { status: 400 }
      )
    }

    // Generate text-based report (PDF generation temporarily disabled due to build complexity)
    const textReport = `TARIFF ENGINEERING ANALYSIS
Generated: ${new Date().toLocaleDateString()}

PRODUCT: ${data.product}

CURRENT CLASSIFICATION:
HTS Code: ${data.currentClassification.hts}
Duty Rate: ${data.currentClassification.rate}
Description: ${data.currentClassification.description}

ENGINEERING OPPORTUNITIES:
${data.opportunities.map((opp: any, idx: number) => `
${idx + 1}. ${opp.modification}
   Current: ${opp.currentHTS} @ ${opp.currentRate}
   New: ${opp.newHTS} @ ${opp.newRate}
   Reduction: ${opp.reduction}
   Confidence: ${opp.confidence}
   Annual Savings: $${opp.savings.annual.toLocaleString()}
   Supporting Rulings: ${opp.rulings.map((r: any) => r.id).join(', ')}

   ${opp.explanation}
`).join('\n')}

TOTAL POTENTIAL SAVINGS: $${data.totalPotentialSavings.toLocaleString()}/year

DISCLAIMER: This analysis is based on publicly available CBP rulings and is provided for
informational purposes only. It does not constitute legal advice or customs brokerage services.
Consult a licensed customs broker before implementing any tariff engineering modifications.

Generated by Tariff Engineer - tariffengineer.vercel.app
Data from CBP CROSS Rulings Database`

    // Return as downloadable text file
    return new NextResponse(textReport, {
      status: 200,
      headers: {
        'Content-Type': 'text/plain',
        'Content-Disposition': `attachment; filename="tariff-analysis-${Date.now()}.txt"`,
      },
    })
  } catch (error) {
    console.error('Report generation error:', error)
    return NextResponse.json(
      { error: 'Failed to generate report' },
      { status: 500 }
    )
  }
}
